### ISSUE TITLE
DWEquipmentBonanza fails to load on Below Zero

### ISSUE THREAD

**Issue by Jsnhlbr5** [DaWrecka/DaWreckasSubnauticaStuff#5]
Looking at the logs, it appears that multiple TechTypes are being added multiple times.  There are also missing assets for some of the upgrades.  (I tried all versions 0.12.0.1 and newer available from [here](https://github.com/DaWrecka/Beta-Mods/tree/main/BelowZero).)
Log file from 0.13.0.4 (Truncated only to remove system info): [qmodmanager_log-SubnauticaZero.txt](https://github.com/DaWrecka/DaWreckasSubnauticaStuff/files/9804922/qmodmanager_log-SubnauticaZero.txt)

**Comment by Jsnhlbr5** [comment]
Found that none of these was the true issue, but a Harmony issue, fixed in a fork by @EldritchCarMaker

**Comment by EldritchCarMaker** [comment]
Several harmony issues, plus a couple of removed classes.

I have the compiled .dll posted in the subnautica modding discord if you want to use it

**Comment by Jsnhlbr5** [comment]
Took some tweaking with the references, but I got your version to compile on my computer; thanks, though.
